-- some functions for general use
require("akriese.functions")
-- load most of the general config (keymaps, globals, Plug, etc)
require("akriese.nvimrc")
-- Plugin setups
require("akriese.nvim-cmp")
require("akriese.treesitter")
require("akriese.nvim-tree")
require("akriese.lspconfig")
require("akriese.telescope")
require("akriese.symbols")
require("akriese.comment")
require("akriese.bufferline")
require("akriese.dap")
require("akriese.scroll")
require("akriese.harpoon")
